CREATE DATABASE IF NOT EXISTS mydb;
USE mydb;

CREATE TABLE IF NOT EXISTS news (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  news_text TEXT,
  image VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS intern (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS workers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    email VARCHAR(50) NOT NULL,
    position VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL
);

INSERT INTO user (login, password) VALUES ('admin', 'admin') ON DUPLICATE KEY UPDATE password='admin';

CREATE USER IF NOT EXISTS 'web'@'localhost' IDENTIFIED BY '123123';
GRANT ALL PRIVILEGES ON mydb.* TO 'web'@'localhost';
FLUSH PRIVILEGES;

